set -e
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts'
curl -sS 'https://docs.agentscope.io/basic-concepts/agent.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/agent.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/agent.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts/agent.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts'
curl -sS 'https://docs.agentscope.io/basic-concepts/context-and-memory.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/context-and-memory.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/context-and-memory.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts/context-and-memory.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts'
curl -sS 'https://docs.agentscope.io/basic-concepts/model.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/model.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/model.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts/model.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts'
curl -sS 'https://docs.agentscope.io/basic-concepts/msg.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/msg.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/msg.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts/msg.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts'
curl -sS 'https://docs.agentscope.io/basic-concepts/tool.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/tool.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/basic-concepts/tool.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/basic-concepts/tool.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks'
curl -sS 'https://docs.agentscope.io/building-blocks/agent.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/agent.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/agent.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks/agent.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks'
curl -sS 'https://docs.agentscope.io/building-blocks/context-and-memory.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/context-and-memory.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/context-and-memory.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks/context-and-memory.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks'
curl -sS 'https://docs.agentscope.io/building-blocks/hooking-functions.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/hooking-functions.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/hooking-functions.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks/hooking-functions.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks'
curl -sS 'https://docs.agentscope.io/building-blocks/models.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/models.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/models.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks/models.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks'
curl -sS 'https://docs.agentscope.io/building-blocks/orchestration.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/orchestration.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/orchestration.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks/orchestration.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks'
curl -sS 'https://docs.agentscope.io/building-blocks/rag.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/rag.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/rag.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks/rag.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks'
curl -sS 'https://docs.agentscope.io/building-blocks/tool-capabilities.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/tool-capabilities.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/building-blocks/tool-capabilities.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/building-blocks/tool-capabilities.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/deploy-and-serve' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/deploy-and-serve'
curl -sS 'https://docs.agentscope.io/deploy-and-serve/agent-as-service.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/deploy-and-serve/agent-as-service.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/deploy-and-serve/agent-as-service.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/deploy-and-serve/agent-as-service.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/deploy-and-serve' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/deploy-and-serve'
curl -sS 'https://docs.agentscope.io/deploy-and-serve/sandbox-and-tool.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/deploy-and-serve/sandbox-and-tool.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/deploy-and-serve/sandbox-and-tool.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/deploy-and-serve/sandbox-and-tool.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs'
curl -sS 'https://docs.agentscope.io/index.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/index.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/index.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/index.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/observe-and-evaluate' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/observe-and-evaluate'
curl -sS 'https://docs.agentscope.io/observe-and-evaluate/evaluation.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/observe-and-evaluate/evaluation.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/observe-and-evaluate/evaluation.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/observe-and-evaluate/evaluation.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/observe-and-evaluate' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/observe-and-evaluate'
curl -sS 'https://docs.agentscope.io/observe-and-evaluate/observability.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/observe-and-evaluate/observability.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/observe-and-evaluate/observability.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/observe-and-evaluate/observability.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/others' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/others'
curl -sS 'https://docs.agentscope.io/others/faq.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/others/faq.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/others/faq.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/others/faq.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents'
curl -sS 'https://docs.agentscope.io/out-of-box-agents/alias.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/alias.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/alias.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents/alias.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents'
curl -sS 'https://docs.agentscope.io/out-of-box-agents/alias-finance.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/alias-finance.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/alias-finance.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents/alias-finance.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents'
curl -sS 'https://docs.agentscope.io/out-of-box-agents/browser-use.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/browser-use.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/browser-use.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents/browser-use.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents'
curl -sS 'https://docs.agentscope.io/out-of-box-agents/data-science.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/data-science.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/data-science.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents/data-science.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents'
curl -sS 'https://docs.agentscope.io/out-of-box-agents/datajuicer-agent.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/datajuicer-agent.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/datajuicer-agent.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents/datajuicer-agent.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents'
curl -sS 'https://docs.agentscope.io/out-of-box-agents/deep-research.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/deep-research.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/deep-research.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents/deep-research.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents'
curl -sS 'https://docs.agentscope.io/out-of-box-agents/evo-trader.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/evo-trader.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/out-of-box-agents/evo-trader.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/out-of-box-agents/evo-trader.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs'
curl -sS 'https://docs.agentscope.io/quickstart.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/quickstart.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/quickstart.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/quickstart.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent'
curl -sS 'https://docs.agentscope.io/tune-agent/model-selection-tuning.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/model-selection-tuning.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/model-selection-tuning.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent/model-selection-tuning.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent'
curl -sS 'https://docs.agentscope.io/tune-agent/model-weights-tuning.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/model-weights-tuning.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/model-weights-tuning.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent/model-weights-tuning.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent'
curl -sS 'https://docs.agentscope.io/tune-agent/prompt-tuning.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/prompt-tuning.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/prompt-tuning.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent/prompt-tuning.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent'
curl -sS 'https://docs.agentscope.io/tune-agent/tune-multi-agents.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/tune-multi-agents.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/tune-multi-agents.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent/tune-multi-agents.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent'
curl -sS 'https://docs.agentscope.io/tune-agent/tune-your-first-agent.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/tune-your-first-agent.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tune-agent/tune-your-first-agent.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tune-agent/tune-your-first-agent.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tutorial' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tutorial'
curl -sS 'https://docs.agentscope.io/tutorial/tutorial_research_agent.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tutorial/tutorial_research_agent.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tutorial/tutorial_research_agent.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tutorial/tutorial_research_agent.md'
mkdir -p '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tutorial' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tutorial'
curl -sS 'https://docs.agentscope.io/tutorial/tutorial_sales_agent.md' -o '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tutorial/tutorial_sales_agent.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/tutorial/tutorial_sales_agent.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/tutorial/tutorial_sales_agent.md'
printf '# AgentScope Docs Mirror\n\nMirrored from https://docs.agentscope.io/ using the official llms.txt index.\n\nSee `llms.txt` for the full page list.\n' > '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/INDEX.md'
cp '/Users/adityatiwari/Burry/mac-butler/references/agentscope_docs/INDEX.md' '/Users/adityatiwari/Burry/Butler Vault/References/AgentScope Docs/INDEX.md'
